### ISSUE TITLE
How to call snapTo if I use functional component? 

### ISSUE THREAD

**Issue by intmainreturn00** [wix-incubator/react-native-interactable#294]
Sample [here](https://github.com/wix/react-native-interactable/blob/master/playground/src/examples/SnapTo.js) shows how to use snapTo from a class-based component for starting the animation by a button click. 

Is there any other way to use `snapTo` for `Interactable.View` inside functional component? If so, could you please provide some sample? 

Thanks in advance and thanks for a great work!

**Comment by manuel-grondona** [comment]
You could useRef, something like this worked for me:

```
const interactableRef = useRef(null)

handlePress = () => {
interactableRef.current.snapTo({ x: 0 })
}

<Interactable.View
    ref={interactableRef}
   .......
>
.........
</Interactable.View>

```

**Comment by ShivamJoker** [comment]
You can also use
`containerRef.current.snapTo({index: 1});`
